import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

import "./globals.css";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-between p-3">
          <h1 className="font-bold text-4xl">Eunlog</h1>
          <div
            className="flex gap-x-3 items-center font-bold text-1xl"
            style={{ color: "#535F70" }}
          >
            <Link href={"/"}>Home</Link>
            <Link href={"/about"}>About</Link>
            <Link href={"/posts"}>Posts</Link>
            <Link href={"/contact"}>Contact</Link>
          </div>
        </header>
        {children}
        <footer className="h-24 bg-stone-200 flex items-end p-5">
          <span className="font-bold text-neutral-400">
            Eunji choi, All rights reserved
          </span>
        </footer>
      </body>
    </html>
  );
}
